# Use the official Elasticsearch image
FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.1

# Disable X-Pack security
RUN elasticsearch-plugin remove x-pack

# Set environment variables
ENV discovery.type=single-node