"""filed

Revision ID: 3a520204900e
Revises: 2ec640bd325d
Create Date: 2024-02-01 14:43:41.288993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a520204900e'
down_revision = '2ec640bd325d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.String(length=50), nullable=True))
        batch_op.drop_column('filed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filed', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('field')

    # ### end Alembic commands ###
