"""fav relationship

Revision ID: 5cf41dc0b0d3
Revises: ed1de0f656bc
Create Date: 2023-12-25 02:44:08.411187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cf41dc0b0d3'
down_revision = 'ed1de0f656bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_edits', schema=None) as batch_op:
        batch_op.drop_column('edited_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_text', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
