"""add username from User model

Revision ID: 63745b5149a9
Revises: 874d398d5345
Create Date: 2023-12-21 23:15:20.245094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63745b5149a9'
down_revision = '874d398d5345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
