"""ajout de la table de correspondance

Revision ID: f8df1871ed0e
Revises: ace7e3878ef6
Create Date: 2023-12-25 01:41:16.004907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8df1871ed0e'
down_revision = 'ace7e3878ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_elasticsearch_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('elasticsearch_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_elasticsearch_mapping')
    # ### end Alembic commands ###
