"""required

Revision ID: fe56d9ff17ef
Revises: 3a520204900e
Create Date: 2024-02-01 17:09:51.225524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe56d9ff17ef'
down_revision = '3a520204900e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('full_text',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nature',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('field',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('field',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nature',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('full_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
